### ISSUE TITLE
`onActivate` for nested routes

### ISSUE THREAD

**Issue by nicholaswyoung** [router5/router5#41] opened 2016-01-06 15:08 UTC
I'm currently refining the `onActivate` Redux middleware example so that the callback is fired for *all active route segments, including children*. As it stands, routes that are defined under `children` in the POJO route definitions file, don't have these callbacks fired.

Is there a better API, other than looping through the `routes` definitions? Can I access nested routes by their name?

**Comment by troch** [comment] 2016-01-06 15:24
You probably need to flatten your array and extract the segments you need. Can you show me your route definitions?

**Comment by nicholaswyoung** [comment] 2016-01-06 15:41
```javascript
const routes = [
  {
    name: 'shop',
    path: '/shop',
    onActivate: (dispatch) => (params) => {
      dispatch(loadProducts(params));
    },
    children: [
      {
        name: 'category',
        path: '/category/:id',
        onActivate: (dispatch) => (params) => {
          dispatch(filterProducts(params.id));
        }
      }
    ]
  },
  {
    name: '404',
    path: '/404'
  },
  {
    name: 'page',
    path: '/*path',
    onActivate: (dispatch) => (params) => {
      dispatch(loadPage(params));
    }
  }
];
```

**Comment by nicholaswyoung** [comment] 2016-01-06 15:45
I know that Router5 concats names, and while I can write the concat behavior in my plugin, that seems like it would be hard to keep in sync.

I'd much rather ask R5 for a list of matching routes, given the `transition-path`.

**Comment by troch** [comment] 2016-01-06 15:48
So you want all active segments? all newly activated segments? Keep in mind R5 does not know about your `onActivate` handlers.

**Comment by nicholaswyoung** [comment] 2016-01-06 15:54
Right. If a child route is activating, I want to include it.

This feature is ideally a userland implementation, but since R5 concats child routes (`shop.category`), it might make sense to have an API where I could ask the Router instance about matches. So:

```javascript
let matches = router.match(['shop', 'shop.category']) // args are the output of transitionPath.
matches = [
  {
    // route definitions for all cases where name matches
    name: 'shop.category',
    onActivate: () => {}
  }
];
```

I would've added the `.` when defining definitions, but that errored when the router initialized.

Does this make sense? For now, I can hack out a solution, but I think an official API would be handy.

**Comment by troch** [comment] 2016-01-06 16:16
Currently r5 stores name and path for each route. It has a registry of `canActivate` functions separately. `onActivate` is different, it doesn't belong to the router, as you said it is userland. r5 only cares about making sure a transition can happen, it doesn't care about what needs to happen on a route change.

I have a repo here: https://github.com/router5/helpers where I can add helper functions to manipulate a manifest of nested routes.

> Since R5 concats child routes

It doesn't. When you use transitionPath, it resolves full node names: https://github.com/router5/transition-path/blob/master/modules/index.js#L1-L5

> I would've added the `.`  when defining definitions, but that errored when the router initialized

That is expected behaviour (from the router perspective). If you add a route like so:

```
const routes = [
  {
    name: 'shop.category',
    path: '/category/:id',
  }
```
R5 will look for the 'shop' node and if found it will add 'category'. So if you do:
```
const routes = [
  {
    name: 'shop',
    path: '/shop',
    children: [
      {
        name: 'shop.category',
        path: '/category/:id',
      }
  ]
}
```
It will try to find the node 'shop' from the node 'shop' to add 'category', hence the error

**Comment by nicholaswyoung** [comment] 2016-01-06 16:33
Should I be using the `children` array when defining routes, or just skip it? If R5's nested states are based on `shop.category` style notation, it seems clearest to ignore the nested array if possible.

**Comment by troch** [comment] 2016-01-06 16:35
It is really up to you. Nested children attributes avoid you to repeat parent segments, which can be a benefit if you nest deeply. It can be a bit less maintainable if you reorganise your routes quite often.

**Comment by nicholaswyoung** [comment] 2016-01-06 16:37
That makes sense. I think that, for now, I won't nest children &mdash; just since it keeps the routes array shallow and simpler to maintain.

Thanks for all of your help!

**Comment by troch** [comment] 2016-01-06 16:38
:+1:

**Comment by troch** [comment] 2016-01-09 21:08
I'm closing this for now.

**Closed by troch** 2016-01-09 21:08 UTC

**Comment by troch** [comment] 2016-01-27 10:04
@nicholaswyoung version >= 2.0.0 registers `canActivate` functions for you, and middleware syntax has slightly changed `router => (toState, fromState[, done]) => ...`. With redux, you get your store (`router => (store, toState, ...) => ...`

**Comment by nicholaswyoung** [comment] 2016-01-27 10:52
@troch So there is no need for custom Redux middleware? Because if I can retrieve the store in `canActivate` router middleware, then it might make sense to drop the `onActivate` handlers.

**Comment by troch** [comment] 2016-01-27 11:32
store was always available in `canActivate`, the novelty is that it is available in middleware functions.

You should not perform data loading in `canActivate`, because you cannot be sure at that point the transition can happen (a child segment `canActivate` method could still fail it). So middleware (router5 or redux) executing `onActivate` handlers is recommended.
